# tasks file for nfs-server
- name: Install nfs-server
  apt:
    update_cache: yes
    name: nfs-kernel-server

- name: Create dir /files
  file:
    path: /files
    state: directory
    owner: nobody
    group: nogroup

- name: Copy config
  template:
    src: exports.j2
    dest: /etc/exports
  notify: restart nfs-kernel-server

- name: Allow access to ssh
  ufw:
    rule: allow
    port: ssh
    state: enabled
  notify: reload ufw

- name: allow access to nfs from web01
  ufw:
    rule: allow
    port: nfs
    from_ip: "{{ hostvars['web01']['openstack']['addresses']['network'] | map(attribute='addr') | first }}"
    state: enabled
  notify: reload ufw

